export interface Surah {
  number: number;
  name: string;
  totalVerses: number;
  juzs: number[];
}

export const SURAH_LIST: Surah[] = [
  { number: 1, name: "Al-Fatihah", totalVerses: 7, juzs: [1] },
  { number: 2, name: "Al-Baqarah", totalVerses: 286, juzs: [1, 2, 3] },
  { number: 3, name: "Ali 'Imran", totalVerses: 200, juzs: [3, 4] },
  { number: 4, name: "An-Nisa'", totalVerses: 176, juzs: [4, 5, 6] },
  { number: 5, name: "Al-Ma'idah", totalVerses: 120, juzs: [6, 7] },
  { number: 6, name: "Al-An'am", totalVerses: 165, juzs: [7, 8] },
  { number: 7, name: "Al-A'raf", totalVerses: 206, juzs: [8, 9] },
  { number: 8, name: "Al-Anfal", totalVerses: 75, juzs: [9, 10] },
  { number: 9, name: "At-Tawbah", totalVerses: 129, juzs: [10, 11] },
  { number: 10, name: "Yunus", totalVerses: 109, juzs: [11] },
  { number: 11, name: "Hud", totalVerses: 123, juzs: [11, 12] },
  { number: 12, name: "Yusuf", totalVerses: 111, juzs: [12, 13] },
  { number: 13, name: "Ar-Ra'd", totalVerses: 43, juzs: [13] },
  { number: 14, name: "Ibrahim", totalVerses: 52, juzs: [13] },
  { number: 15, name: "Al-Hijr", totalVerses: 99, juzs: [14] },
  { number: 16, name: "An-Nahl", totalVerses: 128, juzs: [14] },
  { number: 17, name: "Al-Isra'", totalVerses: 111, juzs: [15] },
  { number: 18, name: "Al-Kahf", totalVerses: 110, juzs: [15, 16] },
  { number: 19, name: "Maryam", totalVerses: 98, juzs: [16] },
  { number: 20, name: "Ta-Ha", totalVerses: 135, juzs: [16] },
  { number: 21, name: "Al-Anbiya'", totalVerses: 112, juzs: [17] },
  { number: 22, name: "Al-Hajj", totalVerses: 78, juzs: [17] },
  { number: 23, name: "Al-Mu'minun", totalVerses: 118, juzs: [18] },
  { number: 24, name: "An-Nur", totalVerses: 64, juzs: [18] },
  { number: 25, name: "Al-Furqan", totalVerses: 77, juzs: [18, 19] },
  { number: 26, name: "Ash-Shu'ara'", totalVerses: 227, juzs: [19] },
  { number: 27, name: "An-Naml", totalVerses: 93, juzs: [19, 20] },
  { number: 28, name: "Al-Qashash", totalVerses: 88, juzs: [20] },
  { number: 29, name: "Al-Ankabut", totalVerses: 69, juzs: [20, 21] },
  { number: 30, name: "Ar-Rum", totalVerses: 60, juzs: [21] },
  { number: 31, name: "Luqman", totalVerses: 34, juzs: [21] },
  { number: 32, name: "As-Sajdah", totalVerses: 30, juzs: [21] },
  { number: 33, name: "Al-Ahzab", totalVerses: 73, juzs: [21, 22] },
  { number: 34, name: "Saba'", totalVerses: 54, juzs: [22] },
  { number: 35, name: "Fatir", totalVerses: 45, juzs: [22] },
  { number: 36, name: "Ya-Sin", totalVerses: 83, juzs: [22, 23] },
  { number: 37, name: "As-Saffat", totalVerses: 182, juzs: [23] },
  { number: 38, name: "Shad", totalVerses: 88, juzs: [23] },
  { number: 39, name: "Az-Zumar", totalVerses: 75, juzs: [23, 24] },
  { number: 40, name: "Ghafir", totalVerses: 85, juzs: [24] },
  { number: 41, name: "Fushshilat", totalVerses: 54, juzs: [24, 25] },
  { number: 42, name: "Asy-Syura", totalVerses: 53, juzs: [25] },
  { number: 43, name: "Az-Zukhruf", totalVerses: 89, juzs: [25] },
  { number: 44, name: "Ad-Dukhan", totalVerses: 59, juzs: [25] },
  { number: 45, name: "Al-Jatsiyah", totalVerses: 37, juzs: [25] },
  { number: 46, name: "Al-Ahqaf", totalVerses: 35, juzs: [26] },
  { number: 47, name: "Muhammad", totalVerses: 38, juzs: [26] },
  { number: 48, name: "Al-Fath", totalVerses: 29, juzs: [26] },
  { number: 49, name: "Al-Hujurat", totalVerses: 18, juzs: [26] },
  { number: 50, name: "Qaf", totalVerses: 45, juzs: [26] },
  { number: 51, name: "Adz-Dzariyat", totalVerses: 60, juzs: [26, 27] },
  { number: 52, name: "At-Thur", totalVerses: 49, juzs: [27] },
  { number: 53, name: "An-Najm", totalVerses: 62, juzs: [27] },
  { number: 54, name: "Al-Qamar", totalVerses: 55, juzs: [27] },
  { number: 55, name: "Ar-Rahman", totalVerses: 78, juzs: [27] },
  { number: 56, name: "Al-Waqi'ah", totalVerses: 96, juzs: [27] },
  { number: 57, name: "Al-Hadid", totalVerses: 29, juzs: [27] },
  { number: 58, name: "Al-Mujadilah", totalVerses: 22, juzs: [28] },
  { number: 59, name: "Al-Hasyr", totalVerses: 24, juzs: [28] },
  { number: 60, name: "Al-Mumtahanah", totalVerses: 13, juzs: [28] },
  { number: 61, name: "As-Shaff", totalVerses: 14, juzs: [28] },
  { number: 62, name: "Al-Jumu'ah", totalVerses: 11, juzs: [28] },
  { number: 63, name: "Al-Munafiqun", totalVerses: 11, juzs: [28] },
  { number: 64, name: "At-Taghabun", totalVerses: 18, juzs: [28] },
  { number: 65, name: "At-Thalaq", totalVerses: 12, juzs: [28] },
  { number: 66, name: "At-Tahrim", totalVerses: 12, juzs: [28] },
  { number: 67, name: "Al-Mulk", totalVerses: 30, juzs: [29] },
  { number: 68, name: "Al-Qalam", totalVerses: 52, juzs: [29] },
  { number: 69, name: "Al-Haqqah", totalVerses: 52, juzs: [29] },
  { number: 70, name: "Al-Ma'arij", totalVerses: 44, juzs: [29] },
  { number: 71, name: "Nuh", totalVerses: 28, juzs: [29] },
  { number: 72, name: "Al-Jinn", totalVerses: 28, juzs: [29] },
  { number: 73, name: "Al-Muzzammil", totalVerses: 20, juzs: [29] },
  { number: 74, name: "Al-Muddatstsir", totalVerses: 56, juzs: [29] },
  { number: 75, name: "Al-Qiyamah", totalVerses: 40, juzs: [29] },
  { number: 76, name: "Al-Insan", totalVerses: 31, juzs: [29] },
  { number: 77, name: "Al-Mursalat", totalVerses: 50, juzs: [29] },
  { number: 78, name: "An-Naba'", totalVerses: 40, juzs: [30] },
  { number: 79, name: "An-Nazi'at", totalVerses: 46, juzs: [30] },
  { number: 80, name: "'Abasa", totalVerses: 42, juzs: [30] },
  { number: 81, name: "At-Takwir", totalVerses: 29, juzs: [30] },
  { number: 82, name: "Al-Infitar", totalVerses: 19, juzs: [30] },
  { number: 83, name: "Al-Muthaffifin", totalVerses: 36, juzs: [30] },
  { number: 84, name: "Al-Insyiqaq", totalVerses: 25, juzs: [30] },
  { number: 85, name: "Al-Buruj", totalVerses: 22, juzs: [30] },
  { number: 86, name: "At-Thariq", totalVerses: 17, juzs: [30] },
  { number: 87, name: "Al-A'la", totalVerses: 19, juzs: [30] },
  { number: 88, name: "Al-Ghasyiyah", totalVerses: 26, juzs: [30] },
  { number: 89, name: "Al-Fajr", totalVerses: 30, juzs: [30] },
  { number: 90, name: "Al-Balad", totalVerses: 20, juzs: [30] },
  { number: 91, name: "Asy-Syams", totalVerses: 15, juzs: [30] },
  { number: 92, name: "Al-Lail", totalVerses: 21, juzs: [30] },
  { number: 93, name: "Ad-Dhuha", totalVerses: 11, juzs: [30] },
  { number: 94, name: "Al-Insyirah", totalVerses: 8, juzs: [30] },
  { number: 95, name: "At-Tin", totalVerses: 8, juzs: [30] },
  { number: 96, name: "Al-'Alaq", totalVerses: 19, juzs: [30] },
  { number: 97, name: "Al-Qadr", totalVerses: 5, juzs: [30] },
  { number: 98, name: "Al-Bayyinah", totalVerses: 8, juzs: [30] },
  { number: 99, name: "Az-Zalzalah", totalVerses: 8, juzs: [30] },
  { number: 100, name: "Al-'Adiyat", totalVerses: 11, juzs: [30] },
  { number: 101, name: "Al-Qari'ah", totalVerses: 11, juzs: [30] },
  { number: 102, name: "At-Takatsur", totalVerses: 8, juzs: [30] },
  { number: 103, name: "Al-'Asr", totalVerses: 3, juzs: [30] },
  { number: 104, name: "Al-Humazah", totalVerses: 9, juzs: [30] },
  { number: 105, name: "Al-Fil", totalVerses: 5, juzs: [30] },
  { number: 106, name: "Quraisy", totalVerses: 4, juzs: [30] },
  { number: 107, name: "Al-Ma'un", totalVerses: 7, juzs: [30] },
  { number: 108, name: "Al-Kautsar", totalVerses: 3, juzs: [30] },
  { number: 109, name: "Al-Kafirun", totalVerses: 6, juzs: [30] },
  { number: 110, name: "An-Nashr", totalVerses: 3, juzs: [30] },
  { number: 111, name: "Al-Lahab", totalVerses: 5, juzs: [30] },
  { number: 112, name: "Al-Ikhlas", totalVerses: 4, juzs: [30] },
  { number: 113, name: "Al-Falaq", totalVerses: 5, juzs: [30] },
  { number: 114, name: "An-Nas", totalVerses: 6, juzs: [30] }
];

export function getSurahsByJuz(juz: number): Surah[] {
  return SURAH_LIST.filter(surah => surah.juzs.includes(juz));
}
